# Generated by Django 5.0.2 on 2024-03-26 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cursos')),
            ],
        ),
    ]
