# Generated by Django 5.0.2 on 2024-03-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('edad', models.PositiveIntegerField()),
                ('nombre_usuario', models.CharField(max_length=255, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cursos_inscritos', models.ManyToManyField(to='myapp.cursos')),
            ],
        ),
    ]
